import torch

DATA_FOLDER = "data"

DUPLICATE_IMAGES_FILE_PATH = f"{DATA_FOLDER}/duplicate_images.txt"

MASKS_FOLDER = f"{DATA_FOLDER}/masks"
PREPROCESSED_FOLDER = f"{DATA_FOLDER}/preprocessed"
PREPROCESSED_MASKS_FOLDER = f"{DATA_FOLDER}/preprocessed_masks"

METADATA_2016_PATH = f"{DATA_FOLDER}/2016_Metadata.csv"
METADATA_2017_PATH = f"{DATA_FOLDER}/2017_Metadata.csv"
METADATA_2018_PATH = f"{DATA_FOLDER}/2018_Metadata.csv"
METADATA_2019_PATH = f"{DATA_FOLDER}/2019_Metadata.csv"
METADATA_2020_PATH = f"{DATA_FOLDER}/2020_Metadata.csv"
METADATA_FITZPATRICK_PATH = f"{DATA_FOLDER}/Fitzpatrick_Metadata.csv"

TRAIN_2016_IMAGE_FOLDER = f"{DATA_FOLDER}/2016_train"
TRAIN_2017_IMAGE_FOLDER = f"{DATA_FOLDER}/2017_train"
TRAIN_2018_IMAGE_FOLDER = f"{DATA_FOLDER}/2018_train"
TRAIN_2019_IMAGE_FOLDER = f"{DATA_FOLDER}/2019_train"
TRAIN_2020_IMAGE_FOLDER = f"{DATA_FOLDER}/2020_train"
TRAIN_FITZPATRICK_IMAGE_FOLDER = f"{DATA_FOLDER}/fitzpatrick_train"

PREPROCESSED_METADATA_2017_PATH = f"{DATA_FOLDER}/df_2017_preprocessed.csv"
PREPROCESSED_METADATA_2019_PATH = f"{DATA_FOLDER}/df_2019_preprocessed.csv"
PREPROCESSED_METADATA_2020_PATH = f"{DATA_FOLDER}/df_2020_preprocessed.csv"
PREPROCESSED_MASKS_METADATA_PATH = f"{DATA_FOLDER}/df_masks_preprocessed.csv"
PREPROCESSED_METADATA_FITZPATRICK_PATH = f"{DATA_FOLDER}/df_fitzpatrick_preprocessed.csv"

CHECKPOINT_FOLDER = "checkpoints"
CLASSIFICATION_MODEL_CHECKPOINT_PATH = f"{CHECKPOINT_FOLDER}/classification_model.pth"
SEGMENTATION_MODEL_CHECKPOINT_PATH = f"{CHECKPOINT_FOLDER}/segmentation_model.pth"

IMAGE_SIZE = 512
SEGMENTATION_IMAGE_SIZE = 512

CLASSIFIER_EPOCHS = 30
SEGMENTATION_EPOCHS = 18

CLASSIFICATION_MODEL_BATCH_SIZE = 32
SEGMENTATION_MODEL_BATCH_SIZE = 16

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
NUM_WORKERS = 8